### ISSUE TITLE
MozFest House decor, lighting, and tablecloths

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/mozfest-design-2019#12]
### Description

We have designed the decor, lighting, and tablecloths for MozFest House in past years. Let's reuse all of it from last year. The tablecloths should just be the generic mozilla branded ones described in https://github.com/MozillaFoundation/mozfest-design-2019/issues/5. If anything needs to be tweaked, let's scope the changes to very minor ones.

#### Components

- [x] Decor
- [x] Lighting

### Reference from last year

**GitHub ticket(s):** 
- [Lighting and decor](https://github.com/MozillaFoundation/mozfest-design-2018/issues/72)
- [Table cloths](https://github.com/MozillaFoundation/mozfest-design-2018/issues/67)

**Comment by gideonthomas** [comment]
Reuse everything from last year.

**Comment by kristinashu** [comment]
Copying info over from last years tickets since we want the same.

### Lightning
Please use warm palette (orange, yellow and pinks from style guide) for lighting and furniture.

### Cushions color

Pantone 137 U + Pantone 232 U 
<img width="388" alt="image" src="https://user-images.githubusercontent.com/2492510/45980805-db383c80-c007-11e8-84a6-944f62b7d3b0.png">

### Table cloth
Hopefully saved them from last year (black with white mozfest house logo).
 
### Logo for cushions and table cloth
Logos exported in [MozFest House lockups folder](https://drive.google.com/open?id=1Hn8HJIcdfnoUnwF1NtI9O2xZa1W8XQ3x)
EPS folder: https://drive.google.com/drive/folders/10xAe82YN7R2uURGQ4nwHukWCvrmEuzN-?usp=sharing
PDF folder: https://drive.google.com/open?id=10LqXhJ5Cd8V0q3-GaqtOXRKzy35IyhEK

cc @sabrinang @marcwalsh

**Comment by sabrinang** [comment]
Tagging @LucieClick-MFHouse so you're informed we are sticking with the same warm MozFest House palette

**Comment by marcwalsh** [comment]
Closing, as it's been used and the items are on site

**Comment by sabrinang** [comment]
*Post-MozFest Documentation*
![10212019-mozfest-house-monday-social-9](https://user-images.githubusercontent.com/2492510/68495771-bbf97000-0205-11ea-97dd-40636bf2d95e.jpg)
![10222019-mozfest-house-tuesday-2](https://user-images.githubusercontent.com/2492510/68495772-bdc33380-0205-11ea-8223-ae33de37624b.jpg)
![10212019-mozfest-house-monday-social-11](https://user-images.githubusercontent.com/2492510/68495775-bf8cf700-0205-11ea-8d03-974edd3263d7.jpg)
