### ISSUE TITLE
Email: Welcome Banner for Template

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2019#18]
**Description:**
Create a banner for the Mozilla Festival e-mail template. The template may be based on the updated, revised version seen in the welcome series/fellowship/OLE email work https://github.com/MozillaFoundation/Design/issues/331. 

**Content:**
Draft email: https://docs.google.com/document/d/1Soo-lCbjQ1Ty5ruK27NiDeHRbYK4F5msKNSGwiLSjq0/edit

**Related Issues:**
Maybe related to sponsorship email graphic: #4 
Last years email related issue: https://github.com/MozillaFoundation/mozfest-design-2018/issues/79
Duplicate: https://github.com/MozillaFoundation/Design/issues/358

**Comment by sabrinang** [comment]
I’ve mocked up the copy and banner on redpen here: https://redpen.io/p/pm35dafbccce937e21
Banner on gdrive: https://drive.google.com/open?id=1qdVl5_h8s-No0jV6CjB2JEsxMNBT2cYZ
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/57335013-3f5ecb00-70d6-11e9-9758-3b3fb6ee7666.png">

@stephaniemcv Confirming we are using the same template as the fellowship/OLE welcome email for Mozilla Festival too?

@KGorr Do you know when you will have the final copy by? and when this email will be sent out?

**Comment by gideonthomas** [comment]
@sabrinang what you have is the final copy now (I've removed draft status). Email will be sent out as soon as people click on the "Sign Up" button on the MozFest page; i.e. it is a welcome email that is automatically sent to people who subscribe for the first time.

**Comment by stephaniemcv** [comment]
@sabrinang Yes, same template.

**Comment by sabrinang** [comment]
Banner exported on gdrive here: https://drive.google.com/file/d/1qbTc56BusB8LjVClwT8nPI6usrmQjUSC/view?usp=sharing

**Comment by kristinashu** [comment]
@stephaniemcv looks like this one will probably get implemented before Fellowship & OLE so should Alex start with this one? I can give him the specs.

**Comment by sabrinang** [comment]
Updated redpen mockups with revised bullet style: https://redpen.io/p/pm35dafbccce937e21 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2492510/57392799-974d0e80-7176-11e9-9e00-80e995c22141.png">

**Comment by stephaniemcv** [comment]
Yes, let's start with this one.

**Comment by kristinashu** [comment]
I've added the specs to [redpen](https://redpen.io/p/pm35dafbccce937e21) but Will and Alex have flagged that it might be better to just include the [white cutout box in the image](https://drive.google.com/file/d/1fDpmtZESDL1Z2ovnIn6mtl4xxMi_2S3S/view?usp=sharing). So we'll try that and see how it goes.

I'm confirming in slack but am also assuming these emails don't need to go through the full moco RASCI approvals since it isn't going to the general list, but please correct me if I'm wrong.

So I think we can close this ticket! I'll just need to QA the email when it's ready, hopefully next week.
