### ISSUE TITLE
Festival Guide

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-design-2019#35]
## Description:
This is a folded pamphlet with only a few pages. The content that will go into this pamphlet includes high-level information about the festival, the theme and the spaces.
### Format
This year's festival guide will take a different form from previous - moving away from the booklet to a fold out pamphlet. 
### Printer and Delivery Requirements
**Printer:** Aspect Press
**Delivery Requirements:** TBC
### Timeline
TBC
### References
[2018 Print Files](https://drive.google.com/open?id=1ojZVYCfF7sva3xI8ZOTZE1RYJfVmEb-Y)
[GitHub Issue](https://github.com/MozillaFoundation/mozfest-design-2018/issues/73)
#### Front
- [ ] Poster (10th Year / Theme Design TBC)
- [ ] Theme Description (Word Count: TBC)
#### Back
- [ ] Schedule Overview
- [ ] Introduction to MozFest (Word Count: TBC)
- [ ] Shortened Participation Guidelines (Word Count: TBC)
- [ ] How To MozFest (Word Count: TBC)
- [ ] Space Icons and Descriptions (Word Count: 15 words per space)
- [ ] Dialogues and Debates (Title, Timings and Names)
- [ ] Sponsors
- [ ] Further Participation CTA
- [ ] Thank You
- [ ] Map

**Comment by sabrinang** [comment]
@siuhoylee During our check-in you mentioned this will be a type of folded format so sharing some reference from 2014s folded poster programme that may be useful since it reminded me of that: 

-  [I took a photo/video so you can see how it folded](https://drive.google.com/drive/folders/1PoJiC50QUCuSoNVkJm9a5a8WdKBR3MAZ?usp=sharing)
- [pdf file](https://drive.google.com/file/d/0BzfN9sXlOXt1THlLNlJxRjdiVXM/view?usp=sharing)

**Comment by siuhoylee** [comment]
@zee-moz  @sabrinang  Here is the Red Pen link to the 2019 Festival Guide flatplan. Note to Zannah: do you think we have enough space for the Dialogues and Debates timings, bear in mind it will also have the Weekend Schedule (I can probably condense this down to halfpage).

**Comment by siuhoylee** [comment]
Here is the Red Pen link to the initial flatplan: https://redpen.io/p/to2737b05e80e6c1e1

**Comment by siuhoylee** [comment]
@zee-moz  We can fit 245 word count for each Dialogues and Debates page but bear in mind the word count will shrink once images are used.

**Comment by siuhoylee** [comment]
@zee-moz  @sabrinang  @marcwalsh    Note to Zannah: Following from our meeting on Tuesday, I have done an initial design and dropped in what relevant text I found for the 2 pages for Space Icons and description. Please see Red Pen link: https://redpen.io/p/to2737b05e80e6c1e1   So this is just an initial starting block. I will add colour and textures to the icons to 1) make them more interesting and and also I guess to follow the Spaces (Thematic) colours  from the guidelines

**Comment by siuhoylee** [comment]
@zee-moz  @sabrinang  @marcwalsh    Note to Zannah: Following from our meeting on Tuesday, I have done an initial design and dropped in what relevant text I found for the 2 pages for Space Icons and description. Please see Red Pen link: https://redpen.io/p/to2737b05e80e6c1e1   So this is just an initial starting block. I will add colour and textures to the icons to 1) make them more interesting and and also I guess to follow the Spaces (Thematic) colours  from the guidelines. Please could you check if the text is fine or not and Sarah just mentioned to me that there will be 3 more Spaces. I think she will speak to about that soon.

**Comment by siuhoylee** [comment]
@zee-moz  @sabrinang  @marcwalsh   
Note to Zannah: I have created a work-in-progress mock of the 3 page Dialogues & Debates/Weekend Schedule. This should give you an idea how it is looking. 
Here is the Red Pen link: https://redpen.io/p/to2737b05e80e6c1e1
The file name is: Dialogues and Debates 3 pages V1

The pages will be divided by talks/panels for Saturday and for Sunday. To accommodate around 20 speakers, it is not necessary to have an image for each. We will get a better idea of word count when I add all the speakers.

**Comment by siuhoylee** [comment]
@zee-moz  @marcwalsh  @sabrinang  In Red Pen there is a V2 Flat Plan. Space Icons and descriptions is now on 2 pages. On the back page is MozFest Further Participation (one line of text), Sponsors and Thank you.

**Comment by siuhoylee** [comment]
@zee-moz  @marcwalsh  @sabrinang   Note to Zannah: I have mocked-up a V2 of the Dialogues and Debates 3 pages. I have just dropped in some text from the previous year in the Weekend Schedule page. I lifted the Speakers text from Mozilla festival website - the text is not consistent I think because some are about the speakers and others are about the session description. I haven't done it yet, but I will add the location for each session. Hopefully this will give you enough to work on reworking the text and wordcount. I will refine/tidy these pages later on.

**Comment by siuhoylee** [comment]
@sabrina  @marcwalsh  V3 of D&D pages are on Red Pen. I will move on to mock up the other pages.

**Comment by siuhoylee** [comment]
@zee-moz  @sabrinang  @marcwalsh  @KevZawacki   In Red Pen I have mocked up the page for Introduction to MozFest and How to MozFest.  The page is called V1 Introduction to MozFest and How to MozFest. Please add any comments. Thanks.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  @zee-moz  In Red Pen there is V1 of Theme Description page. https://redpen.io/p/to2737b05e80e6c1e1Please add any comments.  Thanks.

**Comment by siuhoylee** [comment]
@zee-moz  @sabrinang  @KevZawacki  @marcwalsh   In Red Pen  https://redpen.io/p/to2737b05e80e6c1e1   there is V2 of the Welcome, Theme, Particpation pages. Zannah, I have used the draft copy from the google doc. Please add any comments so far. This is still in working progress. But now I can move on to the Spaces and then Maps pages.

**Comment by siuhoylee** [comment]
@sabrinang  @zee-moz  @marcwalsh  V4 of the Welcome/Theme/Participation/Spaces/Thank You pages are on Red Pen. Note to Sabrina, do we have an icon and colour for MoZone and also Arts & Culture (description required). Awaiting the Coil logo to add to the Thank You/Sponsor page.

**Comment by sabrinang** [comment]
### Regarding icon + colours:

**Experiences**

Colour: Seen on [Mozilla-Festival-2019_Colour-Overview.ai](https://drive.google.com/open?id=1icpMTBOG3afShtZNJ93BMryyn0vxOazR&authuser=sabrina@mozillafoundation.org&usp=drive_fs) or [Style Guide](https://docs.google.com/presentation/d/1TUAe-GJ2ICSRV4VeC_Zur0Fmc3oXY5GJm1U6RV7NIa0/edit?usp=sharing) (slide 17). You can use `#4ca6ff` / `#000000` for experiences
<img width="313" alt="image" src="https://user-images.githubusercontent.com/2492510/65534096-ac230800-deb3-11e9-8201-3640b23b865b.png">

We previously used cubes since there were multiple experiences but since we previously have an icon for Arts & Culture (from 2016) you can use: https://drive.google.com/open?id=0B4Q8pzCpDS_eb2FKT0lJQnlVT2M&authuser=sabrina@mozillafoundation.org&usp=drive_fs
<img width="199" alt="image" src="https://user-images.githubusercontent.com/2492510/65533317-3b2f2080-deb2-11e9-939d-a7cac8076434.png">


If there are more experiences though, you can use the cubes for the set of experiences like we did last year. There was three so we highlighted a cube for each. Cube example: 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/2492510/65533622-d6c09100-deb2-11e9-9cdb-5c1c5dbf70e6.png">

**Mozilla Zone**

Since this is a Mozilla zone, you can use the mozilla white or black highlight colour (or whatever base colour we use for the overarching areas that doesn't have a space colour, previously it was dark navy blue)

Colour: `#FFFFFF` / `#000000` 

You can use the Mozilla [m logo](https://foundation.mozilla.org/en/docs/brand/design/logos/):
<img width="721" alt="image" src="https://user-images.githubusercontent.com/2492510/65535973-56505f00-deb7-11e9-9f06-61ae6586d290.png">

There's also an icon you might find useful: https://drive.google.com/open?id=1EpLuNKgl26MwmMdDDA0ZaBoSLjikdtnh&authuser=sabrina@mozillafoundation.org&usp=drive_fs 
<img width="73" alt="image" src="https://user-images.githubusercontent.com/2492510/65536150-b34c1500-deb7-11e9-9dd0-ae9b52c593eb.png">

Will leave feedback regarding guide in redpen tmrw.

**Comment by siuhoylee** [comment]
@marcwalsh  In Red Pen there is V1 Schedule  https://redpen.io/jsc0b9f83727ac60ae  Please can you confirm the weekend schedule so that I can update it. Thanks.

**Comment by siuhoylee** [comment]
@sabrinang @marcwalsh V5 of the Festival Guide is on Red Pen https://redpen.io/mzc5e40df3728a5097

**Comment by siuhoylee** [comment]
@sabrinang  @zee-moz  @marcwalsh  V6 of the Festival Guide is on Red Pen https://redpen.io/np8bed9c77aefc58b1  I have also done a mockup of how the document folds.

**Comment by siuhoylee** [comment]
@marc  @sabrinang  Note to Marc, in the Sunday Schedule, Session Block 10 it has D&D alongside it. Is this correct. Just let me know. thanks

**Comment by siuhoylee** [comment]
@sabrinang @KevZawacki  @zee-moz  @marcwalsh  Updated V7 of the Guide on Red Pen with design amends and added speaker Katarzyna Szymielewicz to The Future of Digital Policy in Europe. https://redpen.io/jg7aabf8a7879f12c5

**Comment by KevZawacki** [comment]
Thank you, @siuhoylee!!

**Comment by siuhoylee** [comment]
@marcwalsh  @sabrinang  The link to the pdf pages and poster on gdrive is https://drive.google.com/drive/folders/1sKszVAeTFIwC7HESryPhyckHj5jsoSR0  Note to Marc: Please also send to the printers, the page 3d mockups to ensure pages are printed in the correct order.
![Mozilla-Festival-2019-Guide_Pages-7-8-9-10-11-frontcover](https://user-images.githubusercontent.com/53485444/67197333-77dc3200-f3f4-11e9-821e-b2a497a371b7.jpg)
![Mozilla-Festival-2019-Guide_Pages-1-2-3-4-5-6](https://user-images.githubusercontent.com/53485444/67197350-81fe3080-f3f4-11e9-8bbd-40b883b1a070.jpg)
<img width="1496" alt="Page-mockup_pages-7-8-9-10-11-frontcover" src="https://user-images.githubusercontent.com/53485444/67197455-bd006400-f3f4-11e9-88dc-f613de64e0bc.png">
<img width="1496" alt="Page-mockup_pages-1-2-3-4-5-6" src="https://user-images.githubusercontent.com/53485444/67197476-c38edb80-f3f4-11e9-9bad-8be6f2b215d6.png">

**Comment by marcwalsh** [comment]
Sent to print thanks everyone!

**Comment by plwt** [comment]
Having not picked up a copy at the Festival, please could I have a copy of the .pdf?

**Comment by sabrinang** [comment]
@SeburoSUMO There is an online version of the festival guide here: https://issuu.com/mozfest/docs/mozilla-festival-guide-2019

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
Distributed at registration desk
![48997771963_6a7a53e67d_k](https://user-images.githubusercontent.com/2492510/68511139-1efcfe00-022a-11ea-8fa5-2227a86e9f77.jpg)
![IMG_20191108_130055](https://user-images.githubusercontent.com/2492510/68511123-160c2c80-022a-11ea-9823-9cd6027cfc04.jpg)
![IMG_20191108_130024](https://user-images.githubusercontent.com/2492510/68511122-160c2c80-022a-11ea-91d8-56b91b347a53.jpg)
