### ISSUE TITLE
Festival Guide Poster 

### ISSUE THREAD

**Issue by siuhoylee** [MozillaFoundation/mozfest-design-2019#48]
A2 Poster when folded out from the weekend Festival Guide Pamphlet. Some of the ideas we spoke from meetings and brainstorming was that we liked the idea of it being a participatory piece where people can write on them and stick up on walls which proved popular in previous years. We ought to brand it as 10th anniversary with the motif and pattern and or this year's theme which is Healthy AI. The poster can be either landscape or portrait.

**Comment by siuhoylee** [comment]
@sabrinang  @zee-moz  @marcwalsh  Here is the Red Pen link to the Poster design V1. https://redpen.io/p/psac9a7bea0269063f   Please add any comments. Thanks.

**Comment by zee-moz** [comment]
My thoughts on this design: 

- I don't think we should use  language from Chad's blog post because it introduces yet another set of words presented as a slogan which could muddy our messaging, and it leaves out some concepts (like decentralization, privacy, and web lit) that are core issues. 
- We might do better by focusing on the Festival itself, rather than the internet, so we have more flexibility with our copy.  This might be a good place for some version of  "Come with an idea, leave with a community." 
- It would also be cool to have the poster reflect more directly the celebratory feel of our 10th anniversary-- to me the design feels very reserved and matter of fact, and not inspirational or joyful
- This version seems really close x to something we did in past years (as mentioned above), so it would be nice to get something fresh and different. 
- Also are we envisioning them being stuck on the walls at the festival, or elsewhere, after the festival? 

I'll think a bit about alternate content. As this is a lot of our guide real estate, is it worth getting the four of us in a meeting to discuss? @siuhoylee @marcwalsh @sabrinang

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh @zee-moz  There is a V2 poster in Red Pen https://redpen.io/p/psac9a7bea0269063f  I just had an idea it may or may not work but its good to try and share it and open to feedback.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  @zee-moz  I've just iterated on V2 design. V3 is on Red Pen too. Adding in the radiating elements from the Volunteer T-Shirt.

**Comment by siuhoylee** [comment]
@sabrinang  @marcwalsh  V5 of the Festival Guide is on Red Pen https://redpen.io/mzc5e40df3728a5097

**Comment by siuhoylee** [comment]
@sabrinang  @zee-moz  @marcwalsh  Here is the Red Pen link to the latest version of the Festival Guide pamphlet poster https://redpen.io/zo7c87028dc7a15870

**Comment by zee-moz** [comment]
@siuhoylee @sabrinang @marcwalsh i wonder if making the type smaller so you see more complete phrases would help with understanding the pattern better? love the colors!

**Comment by siuhoylee** [comment]
@sabrinang  @zee-moz  @marcwalsh  V5 of the updated Festival Guide Poster is on Red Pen following feedback from Sabrina and Zannah. There is another image to show the fold lines.  https://redpen.io/cse976f40f445975e1

**Comment by siuhoylee** [comment]
@sabrina  @marcwalsh  I made the last few minor amends - centered the blank text area, lowered the motif and tidied the area around the Mozilla Festival logo. Here is the gdrive link to the final artwork. https://drive.google.com/drive/folders/1XGGk1BHQRi87Fzoz-0XRu_3PMD01Iy7j
![V6 Festival Guide A2 Poster](https://user-images.githubusercontent.com/53485444/67167119-fbaf0380-f38d-11e9-9918-e6b33f092e56.jpg)

**Comment by sabrinang** [comment]
@siuhoylee The revised design looks good and balanced. Folds, bleeds and outlined text is good in the doc too. R+

**Comment by marcwalsh** [comment]
Sent to print - thank you!

**Comment by sabrinang** [comment]
**Post-MozFest Documentation**
distributed at registration
![48997771963_6a7a53e67d_k](https://user-images.githubusercontent.com/2492510/68510712-0dffbd00-0229-11ea-9a86-d1f3e082b96f.jpg)
![IMG_20191108_130016](https://user-images.githubusercontent.com/2492510/68510641-e577c300-0228-11ea-92a3-ec66c919a7ff.jpg)
